modified
ccaiazza/uiip pull request #38
Opened 2019-03-03 18:41 UTC by Samasol

2019-03-04 10:33 UTC, deborahvinciguerra requested changes

2019-03-04 10:33 UTC, deborahvinciguerra commented on hospital/hospitalcore/resources/hospitalcore-items.xml
> +						type="java.lang.String">
deve essere mandatorio e unique

2019-03-04 10:33 UTC, deborahvinciguerra commented on hospital/hospitalcore/resources/hospitalcore-items.xml
>  				jaloclass="org.training.hospital.core.jalo.Hospital">
stai utizzando al jalo class di hospital

2019-03-04 10:33 UTC, deborahvinciguerra commented on hospital/hospitalcore/resources/hospitalcore-items.xml
>  				jaloclass="org.training.hospital.core.jalo.Hospital">
stai utilizzando la jalo class di hospital

2019-03-04 10:33 UTC, deborahvinciguerra commented on hospital/hospitalcore/resources/hospitalcore-items.xml
>  					<attribute qualifier="name"
perche il nome è localizzato? è una persona perchè non hai esteso User

2019-03-04 10:33 UTC, deborahvinciguerra commented on hospital/hospitalcore/resources/hospitalcore-items.xml
>  						<persistence type="dynamic"
verificare se serve il modificatore per l'attributo dinamico o sei i valori di default vanno bene

2019-03-06 10:13 UTC, ccaiazza requested changes

2019-03-06 10:13 UTC, ccaiazza commented on hospital/hospitalcore/resources/hospitalcore-items.xml
> +			</targetElement>
perchè hai messo partof?

2019-03-06 10:13 UTC, ccaiazza commented on hospital/hospitalcore/resources/hospitalcore-items.xml
> +						<modifiers unique="true" />
basta mettere "code" inutile mettere "codeReparto" dato che è un attributo diretto di Reparto così anche come "name" e gli altri

inoltre il codice del reparto deve essere mandatorio non basta l'univocità

2019-03-06 10:13 UTC, ccaiazza commented on hospital/hospitalcore/resources/hospitalcore-items.xml
> +					<attribute qualifier="dateEntry" type="java.util.Date">
arricchisci Head e Patient con altri attributi

2019-03-25 15:22 UTC, merged