Feature/hybris monday
ccaiazza/uiip pull request #39
Opened 2019-03-04 17:32 UTC by citamm

2019-03-05 11:52 UTC, deborahvinciguerra requested changes

2019-03-05 11:52 UTC, deborahvinciguerra commented on custom/hospital/hospitalcore/resources/hospitalcore-items.xml
> +			<sourceElement type="Patient" qualifier="list_patient"
non utilizzare simboli nei qualifier metti il nome al plurale patients

2019-03-05 11:52 UTC, deborahvinciguerra commented on custom/hospital/hospitalcore/resources/hospitalcore-items.xml
> +					<attribute qualifier="surnamePatient"
estendi Customer che contiene già le informazioni anagrafiche

2019-03-05 11:52 UTC, deborahvinciguerra commented on custom/hospital/hospitalcore/resources/hospitalcore-items.xml
> +					<attribute qualifier="entryDate" type="java.lang.String">
per le date devi utilizzare il tipo Date

2019-03-05 11:52 UTC, deborahvinciguerra commented on custom/hospital/hospitalcore/resources/hospitalcore-items.xml
> +			<itemtype code="Head" extends="User" autocreate="true"
estendi Customer che contiene già le informazioni anagrafiche

2019-03-06 10:00 UTC, ccaiazza requested changes

2019-03-06 10:00 UTC, ccaiazza commented on custom/hospital/hospitalcore/resources/hospitalcore-items.xml
> +					partof="true" />
Perchè hai messo partof?

2019-03-06 10:00 UTC, ccaiazza commented on custom/hospital/hospitalcore/resources/hospitalcore-items.xml
arricchisci con altri attributi (es. specializzazione, iscrizione all'albo, ecc..)

2019-03-06 10:00 UTC, ccaiazza commented on custom/hospital/hospitalcore/insert.impex
sistemare gli impex in modo tale da rispettare i cambiamenti fatti agli items (es. list_patient -> patients)

2019-03-06 10:00 UTC, ccaiazza commented on custom/hospital/hospitalcore/resources/hospitalcore-items.xml
>  						type="java.lang.String">
basta mettere "code" inutile mettere "codeReparto" dato che è un attributo diretto di Reparto così anche come "name" e gli altri

2019-03-06 10:00 UTC, ccaiazza commented on custom/hospital/hospitalcore/resources/hospitalcore-items.xml
> +						<description>Data uscita</description>
anche qui arricchiamo con altri attributi (es. patologia)

2019-03-19 11:22 UTC, deborahvinciguerra requested changes

2019-03-19 11:22 UTC, deborahvinciguerra commented on custom/hospital/hospitalcore/src/org/training/hospital/core/dao/impl/DefaultHeadDao.java
>  		final String hospitalName = "Cardarelli";
il name lo devi passare come parametro

2019-03-19 11:22 UTC, deborahvinciguerra commented on custom/hospital/hospitalcore/src/org/training/hospital/core/dao/impl/DefaultHospitalDao.java
> +	{
se hai più ospedali quale ti torna?

2019-03-19 11:22 UTC, deborahvinciguerra commented on custom/hospital/hospitalcore/src/org/training/hospital/core/handler/DynamicAttributesNumberPathology.java
> +		return item.getPathologies().size() + " ";
metti null check, se il paziente non ha patologie va in nullPointerException

2019-03-19 11:22 UTC, deborahvinciguerra commented on custom/hospital/hospitalcore/src/org/training/hospital/core/service/PathologyService.java
> +	public List<PathologyModel> getPathologyByName(String name);
nel service utilizza la name convention get for nel dao find by

2019-03-25 15:41 UTC, closed without merging